language: "perl"
perl:
  - "5.18"
  - "5.16"

#before_install:
#    - cpanm Test::Pod # optional dependency
#
install:
    - cpanm --quiet --installdeps --notest .

script: "perl wbic32.pl dry-run"
# branches:
#   only:
#     - master
notifications:
  recipients:
    - wbic16@gmail.com
  email:
    on_success: change
    on_failure: always
#env:
