language: "perl"
perl:
  - "5.18"
  - "5.16"

#before_install:
#    - cpanm Test::Pod # optional dependency
#
install:
    - cpanm -v --installdeps --notest --mirror http://cpan.mirrors.travis-ci.org .

script: "perl -c wbic32.pl"
# branches:
#   only:
#     - master
notifications:
  recipients:
    - wbic16@gmail.com
  email:
    on_success: change
    on_failure: always
#env:
